name: Learning GitHub actions

# Reference documentation: https://docs.github.com/en/actions/reference

# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    branches:
      - deploy2

# GitHub secrets are stored in
# https://github.com/[your_repo]/settings/secrets/actions
# for example:
#  https://github.com/w3c/pointerevents/settings/secrets/actions

jobs:

# All of the following jobs will run in parallel

  aria-deploy:
    name: Deploy to ARIA to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        run: |
          git clone --depth=3 --branch=main https://github.com/w3c/aria.git .
      - name: Checkout my repository
        run: |
          git clone --depth=3 --branch=deploy2 https://github.com/plehegar/testing.git plhtesting
      - name: Build the specification
        run: |
          git clone --depth=1 --branch=gh-pages https://github.com/plehegar/testing.git gh-pages
          rm -rf gh-pages/common gh-pages/img
          cp -R common img gh-pages
          curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/aria/main/index.html -o gh-pages/index.html -f  --retry 3
      - name: Deploy
        run: plhtesting/.github/scripts/deploy.sh
        env:
          BRANCH: gh-pages
          LOCAL_DIR: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}