name: Learning GitHub actions

# Reference documentation: https://docs.github.com/en/actions/reference

# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    branches:
      - rights

# GitHub secrets are stored in
# https://github.com/[your_repo]/settings/secrets/actions
# for example:
#  https://github.com/w3c/pointerevents/settings/secrets/actions

jobs:

# All of the following jobs will run in parallel


  use-deploy-script-git-command:
    name: Using a shell script to deploy a build folder on a GitHub branch with the git command
    runs-on: ubuntu-latest
    steps:
      - name: script
        run: |
          mkdir output
          git clone --depth=1 --branch=gh-pages-3 https://github.com/plehegar/testing.git output
          echo "$RANDOM" >>output/numbers.md
      - name: deploy
        run: .github/scripts/deploy.sh
        env:
          BRANCH: gh-pages-3
          LOCAL_DIR: output
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
