name: Learning GitHub actions
on: [push]
jobs:
  use-node:
    name: Using NodeJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm start
  use-script:
    name: Using a shell script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/scripts/build.sh
        shell: bash
  use-script-2:
    name: Using a shell script inline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        cd foobar
        echo $PWD
  use-python:
    runs-on: ubuntu-latest
    name: Using a python script
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - run: pip install aiohttp
      - run: python index.py
  use-script-and-python:
    runs-on: ubuntu-latest
    name: Using a shell and a python script
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - run: ./python.sh
        shell: bash
  use-irc:
    runs-on: ubuntu-latest
    name: Notifying IRC
    steps:
      - name: Setup IRC notifier
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#github-irc-notify'
          server: irc.w3.org
          port: 6667
          tls: false
          nickname: dummy-irc-github
          message: |
            ${{ github.actor }} pushed to ${{ github.repository }} commit ${{ github.sha }}
