name: Learning GitHub actions
on:
  push:
    branches:
      - main
jobs:
  use-node:
    name: Using NodeJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm start
  use-script:
    name: Using a shell script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # git update-index --chmod +x ./.github/scripts/build.sh
      - run: ./.github/scripts/build.sh
        shell: bash
  use-script-2:
    name: Using a shell script inline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd foobar
          echo $PWD
        shell: bash
  use-java:
    name: Using a java program
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
- run: java -cp java HelloWorldApp
  use-python:
    runs-on: ubuntu-latest
    name: Using a python script
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - run: pip install aiohttp
      - run: python index.py
  use-script-and-python:
    runs-on: ubuntu-latest
    name: Using a shell and a python script
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      # git update-index --chmod +x ./python.sh
      - run: ./python.sh
        shell: bash
  use-irc:
    runs-on: ubuntu-latest
    name: Notifying IRC
    steps:
      - name: Setup IRC notifier
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#github-irc-notify'
          server: irc.w3.org
          port: 6667
          tls: false
          nickname: dummy-irc-github
          message: |
            ${{ github.actor }} pushed to ${{ github.repository }} commit ${{ github.sha }}
  use-deploy-script:
    name: Using a shell script to deploy a build folder on a GitHub branch
    runs-on: ubuntu-latest
    env:
      FOLDER: deploybuild
    steps:
      - uses: actions/checkout@v2
      # git update-index --chmod +x ./.github/scripts/build-output.sh
      - run: ./.github/scripts/build-output.sh
        shell: bash
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          # FOLDER is already set up so no need to repeat here)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
