name: Learning GitHub actions

# Reference documentation: https://docs.github.com/en/actions/reference

# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    branches:
      - tex2mathml

# GitHub secrets are stored in
# https://github.com/[your_repo]/settings/secrets/actions
# for example:
#  https://github.com/w3c/pointerevents/settings/secrets/actions

jobs:

# All of the following jobs will run in parallel

  use-node:
    name: Using tex2mathml
    runs-on: ubuntu-latest
    steps:
      # the following step will checkout your github repository
      - uses: actions/checkout@v2
      # the following step will install nodejs, including npm
      - uses: actions/setup-node@v2
      - run: npm install tex2mathml
      - run: tex2mathml
